### ISSUE TITLE
"The following file does not exist:"  error

### ISSUE THREAD

**Issue by jiangpuxuan** [COMBINE-lab/roe#1]
Thank you for your help in my last issue in Alevin-fry.  I try to use `roe` to make my splici index.
Here is my code:
```
genome_path <- system.file("/Array-Tuqiang/pxjiang/data/f30_RNA_ens_cellranger/Oryzias_latipes.ASM223467v1.94.gtf", package = "roe")
gtf_path <- system.file("/Array-Tuqiang/pxjiang/data/f30_RNA_ens_cellranger/Oryzias_latipes.ASM223467v1.dna_sm.toplevel.fa", package = "roe")
#extra_spliced = system.file("extdata/extra_spliced.txt", package = "roe")
#extra_unspliced = system.file("extdata/extra_unspliced.txt", package = "roe")
filename_prefix = "transcriptome_splici"
output_dir = tempdir()
read_length = 5
flank_trim_length = 2

make_splici_txome(
  genome_path = genome_path,
  gtf_path = gtf_path,
  read_length = read_length,
  output_dir = output_dir,
  flank_trim_length = flank_trim_length,
  filename_prefix = filename_prefix,
  #extra_spliced = extra_spliced,
  #extra_unspliced = extra_unspliced,
  dedup_seqs = FALSE,
  no_flanking_merge = FALSE
)
grep("transcriptome_splici", dir(output_dir), value = TRUE)
```

Here is the error code:
```
Error in .make_splici_txome(genome_path = genome_path, gtf_path = gtf_path, : The following file does not exist:
```

I refer to the  `make_splici_transcriptome.R` :
```
  if (!file.exists(gtf_path)) {
    stop("The following file does not exist: \n", gtf_path)
  }
  # make sure fasta file exists
  if (!file.exists(genome_path)) {
    stop("The following file does not exist: \n", genome_path)
  }
  
```
The errorcode indicated that my `gtf` or `.fa` did not exist. However, they are accessible.

Thank you for your help !

**Comment by rob-p** [comment]
cc @DongzeHE

**Comment by DongzeHE** [comment]
Hello @jiangpuxuan,

Thanks so much for using alevin-fry!

I realize that the example we provided is a little bit confusing. The reason why we use `system.file()` is that we want to locate the example files in the source folder of `roe`. However, in your case, you can just set

```R
genome_path <- "/Array-Tuqiang/pxjiang/data/f30_RNA_ens_cellranger/Oryzias_latipes.ASM223467v1.94.gtf"
gtf_path <- "/Array-Tuqiang/pxjiang/data/f30_RNA_ens_cellranger/Oryzias_latipes.ASM223467v1.dna_sm.toplevel.fa"

```
What's more, I saw that you set `read_length = 5`. We would recommend you to set `read_length` as the read length of the experiment you are running. 

Please let me know if you have any further questions!

Best,
Dongze

**Comment by DongzeHE** [comment]
BTW, I updated the [RNA-velocity tutorial](https://combine-lab.github.io/alevin-fry-tutorials/2021/alevin-fry-velocity/) today based on your findings. The updated tutorial should give you enough information to run the RNA velocity analysis end to end. Please give it a try! One thing to notice is that currently pyroe haven't been added into Bioconda, so you may need to run `pip install pyroe` to install it.

**Comment by jiangpuxuan** [comment]
> Hello @jiangpuxuan,
> 
> Thanks so much for using alevin-fry!
> 
> I realize that the example we provided is a little bit confusing. The reason why we use `system.file()` is that we want to locate the example files in the source folder of `roe`. However, in your case, you can just set
> 
> ```r
> genome_path <- "/Array-Tuqiang/pxjiang/data/f30_RNA_ens_cellranger/Oryzias_latipes.ASM223467v1.94.gtf"
> gtf_path <- "/Array-Tuqiang/pxjiang/data/f30_RNA_ens_cellranger/Oryzias_latipes.ASM223467v1.dna_sm.toplevel.fa"
> ```
> 
> What's more, I saw that you set `read_length = 5`. We would recommend you to set `read_length` as the read length of the experiment you are running.
> 
> Please let me know if you have any further questions!
> 
> Best, Dongze

Thank you for the help. I am runing the `Mapping the data to obtain a RAD file` step, and until now everything is OK.

**Comment by rob-p** [comment]
Dear @jiangpuxuan,

  Were you able to successfully run the rest of the pipeline?  If `roe` is working properly for you, let us know and we can close this issue.

Thanks!
Rob

**Comment by jiangpuxuan** [comment]
> Dear @jiangpuxuan,
> 
> Were you able to successfully run the rest of the pipeline? If `roe` is working properly for you, let us know and we can close this issue.
> 
> Thanks! Rob

Dear Bob,
From what I have seen so far, `roe` works well with `scvelo` and `cellrank` pipeline.
Thank you!

**Comment by rob-p** [comment]
Thanks! I’ll close this issue for now then @jiangpuxuan, but if you run into any other issues feel free to open an issue or, if you have any broader questions, feel free to start a GitHub “discussion “ in the alevin-fry repo!
